---
name: ✨ Feature Request
about: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: ["copilot"]
---

## 🎯 Feature Description
A clear and concise description of the feature you'd like to see.

## 🤔 Problem Statement
Describe the problem this feature would solve. What are you trying to accomplish?

## 💡 Proposed Solution
Describe how you envision this feature working.

## 🔄 Alternatives Considered
Have you considered any alternative solutions or features?

## 📊 Use Cases
Provide specific examples of how this feature would be used.

## 🎨 Additional Context
Add any other context, mockups, or examples about the feature request here.

## ✅ Acceptance Criteria
What would need to be true for this feature to be considered complete?
- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3
